// <auto-generated />
namespace Quản_Lý_Coffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class master : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(master));
        
        string IMigrationMetadata.Id
        {
            get { return "201812231919054_master"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
